package com.bancolombia.mercadolibreempresas.models.businessrules;

public enum NumeralsForms 
{
       FORMULARY_ONE_LAST,FORMULARY_ONE_PENULTIMATE,FORMULARY_TWO_LAST,FORMULARY_TWO_PENULTIMATE,
       FORMULARY_THREE_LAST,FORMULARY_THREE_PENULTIMATE,FORMULARY_FOUR_LAST,FORMULARY_FOUR_PENULTIMATE,
       FORMULARY_FIVE_LAST,FORMULARY_FIVE_PENULTIMATE
}
